segment_write_key:
  default: ""
  description: "The Write Key for your Segment Source"
user_id_strategy:
  type: enum
  choices:
    - email
    - external_id
    - anonymous_id
    - discourse_id
  default: email
  description: "*If anonymous_id is selected, no user_id will be sent which will allow merge on email address. All other options include anonymous_id + user_id. Tip: To carry your anonymous_id from your main site, use the Segmemt Querystring API."
include_user_email:
  default: false
  description: "Include user's email address in identify payload"
track_users:
  default: true
  description: "Call the Segment identify function when a user logs in"
track_page:
  default: false
  description: "Track page visits by page type (tracks the latest, categories, category, tags, and topic pages)"
track_topic_creation:
  default: false
  description: "Track topic creation"
track_post_creation:
  default: false
  description: "Track post creation"
track_likes:
  default: false
  description: "Track likes"
track_flags:
  default: false
  description: "Track flags"
track_bookmarks:
  default: false
  description: "Track bookmarks"
extend_content_security_policy:
  type: list
  default: "script_src: https://cdn.segment.com/analytics.js"